"""Repository Interfaces - 의존성 역전을 위한 추상화"""

from typing import Protocol

from app.models.article_model import Article
from app.models.user_model import User


class UserRepositoryInterface(Protocol):
    def get_by_id(self, user_id: int) -> User | None: ...
    def get_by_email(self, email: str) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def create(self, email: str, username: str, password: str) -> User: ...
    def update(self, user: User) -> User: ...


class ArticleRepositoryInterface(Protocol):
    def get_by_slug(self, slug: str) -> Article | None: ...
    def get_all(
        self, author_id: int | None = None, article_ids: list[int] | None = None
    ) -> list[Article]: ...
    def create(
        self, slug: str, title: str, description: str, body: str, author_id: int
    ) -> Article: ...
    def update(self, article: Article, **kwargs) -> Article: ...
    def delete(self, article: Article) -> None: ...


class TagRepositoryInterface(Protocol):
    def add_tags_to_article(self, article_id: int, tag_names: list[str]) -> None: ...
    def get_tags_for_article(self, article_id: int) -> list[str]: ...
    def get_article_ids_by_tag(self, tag_name: str) -> list[int]: ...
    def get_all_tags(self) -> list[str]: ...


class FavoriteRepositoryInterface(Protocol):
    def create(self, user_id: int, article_id: int) -> None: ...
    def delete(self, user_id: int, article_id: int) -> None: ...
    def get_article_ids_by_user(self, user_id: int) -> list[int]: ...
    def is_favorited(self, user_id: int, article_id: int) -> bool: ...
    def count_by_article(self, article_id: int) -> int: ...


class CommentRepositoryInterface(Protocol):
    def get_by_id(self, comment_id: int): ...
    def get_by_article_id(self, article_id: int) -> list: ...
    def create(self, body: str, author_id: int, article_id: int): ...
    def delete(self, comment) -> None: ...


class FollowRepositoryInterface(Protocol):
    def create(self, follower_id: int, followee_id: int): ...
    def delete(self, follower_id: int, followee_id: int) -> bool: ...
    def is_following(self, follower_id: int, followee_id: int) -> bool: ...
