"""Repository Interfaces - 의존성 역전을 위한 추상화"""

from typing import Optional, Protocol

from app.models.user_model import User


class UserRepositoryInterface(Protocol):
    """유저 저장소 인터페이스"""

    def get_by_id(self, user_id: int) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def get_by_username(self, username: str) -> Optional[User]: ...
    def create(self, email: str, username: str, password: str) -> User: ...
    def update(self, user: User) -> User: ...
